[tool.poetry]
name = "perfect"
version = "0.1.0"
description = ""
authors = ["HAN WENHAO <h898803709@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
prefect = "^2.19.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
